const fs = require^('fs^'); 
const content = fs.readFileSync^('E:/00 - AI/Ontology/repo-main/src/store/ontology-store.ts', 'utf8'^); 
const t = content.indexOf^('deleteStateMachine: (smId) => {'^); 
const endOfDeleteSm = content.indexOf^('  },', content.indexOf^('},', content.indexOf^('},', t^) + 1^) + 1^) + 4; 
const exactDeleteSmStr = content.substring^(t, endOfDeleteSm^); 
let actionMethodsStr =  
addAction: (action) => { set((state) => { if (!state.project) return state; const currentModel = state.project.behaviorModel || { id: generateId(), name: \\\\行为模型\, version: '1.0.0', domain: state.project.domain.id, stateMachines: [], actions: [], functions: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; return { project: { ...state.project, behaviorModel: { ...currentModel, actions: [...(currentModel.actions || []), action], updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); }, 
updateAction: (actionId, action) => { set((state) => { if (!state.project?.behaviorModel) return state; return { project: { ...state.project, behaviorModel: { ...state.project.behaviorModel, actions: state.project.behaviorModel.actions.map((a) => (a.id === actionId ? action : a)), updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); }, 
deleteAction: (actionId) => { set((state) => { if (!state.project?.behaviorModel) return state; return { project: { ...state.project, behaviorModel: { ...state.project.behaviorModel, actions: state.project.behaviorModel.actions.filter((a) => a.id !== actionId), updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); }, 
addFunction: (func) => { set((state) => { if (!state.project) return state; const currentModel = state.project.behaviorModel || { id: generateId(), name: \\\\行为模型\, version: '1.0.0', domain: state.project.domain.id, stateMachines: [], actions: [], functions: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; return { project: { ...state.project, behaviorModel: { ...currentModel, functions: [...(currentModel.functions || []), func], updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); }, 
updateFunction: (funcId, func) => { set((state) => { if (!state.project?.behaviorModel) return state; return { project: { ...state.project, behaviorModel: { ...state.project.behaviorModel, functions: state.project.behaviorModel.functions.map((f) => (f.id === funcId ? func : f)), updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); }, 
deleteFunction: (funcId) => { set((state) => { if (!state.project?.behaviorModel) return state; return { project: { ...state.project, behaviorModel: { ...state.project.behaviorModel, functions: state.project.behaviorModel.functions.filter((f) => f.id !== funcId), updatedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() } }; }); },; 
let newContent = content.replace^(exactDeleteSmStr, exactDeleteSmStr + '\n' + actionMethodsStr^); 
newContent = newContent.replace^(/BusinessScenario,\\n\\s*StateMachine,\\n\\s*Rule,/g, 'BusinessScenario,\\n  StateMachine,\\n  Action,\\n  FunctionDefinition,\\n  Rule,'^); 
newContent = newContent.replace^(/deleteStateMachine: \\(smId: string\\) => void;\\n\\n\\s*\\/\\/ 规则模型操作/g, 'deleteStateMachine: (smId: string) => void;\\n  \\n  addAction: (action: Action) => void;\\n  updateAction: (actionId: string, action: Action) => void;\\n  deleteAction: (actionId: string) => void;\\n  \\n  addFunction: (func: FunctionDefinition) => void;\\n  updateFunction: (funcId: string, func: FunctionDefinition) => void;\\n  deleteFunction: (funcId: string) => void;\\n  \\n  // 规则模型操作'^); 
fs.writeFileSync^('E:/00 - AI/Ontology/repo-main/src/store/ontology-store.ts', newContent^); 
